// AUTO-GENERATED by scripts/build-gallery-manifest.mjs — do not edit by hand.
// Regenerate with `npm run gallery:manifest` (runs automatically on build).

import type { GalleryManifest } from "@/types/gallery";

export const galleryManifest: GalleryManifest = [
  {
    "slug": "bedroom",
    "images": [
      {
        "src": "/images/gallery/bedroom/Bedroom-1.jpg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/images/gallery/bedroom/Bedroom-3.png",
        "width": 1188,
        "height": 1324
      },
      {
        "src": "/images/gallery/bedroom/Bedroom-4.png",
        "width": 941,
        "height": 1672
      },
      {
        "src": "/images/gallery/bedroom/Bedroom-5.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/bedroom/Bedroom-6.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/bedroom/bedroom-7.jpeg",
        "width": 1536,
        "height": 1024
      },
      {
        "src": "/images/gallery/bedroom/image%20-2.png",
        "width": 941,
        "height": 1672
      }
    ]
  },
  {
    "slug": "false-ceiling",
    "images": [
      {
        "src": "/images/gallery/false-ceiling/ceilin-3.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/false-ceiling/ceilin-4.png",
        "width": 1510,
        "height": 1041
      },
      {
        "src": "/images/gallery/false-ceiling/Ceiling%20-1.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling%20-2.png",
        "width": 1102,
        "height": 1427
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling%20-9.png",
        "width": 1218,
        "height": 1292
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-2.png",
        "width": 1127,
        "height": 1395
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-5.png",
        "width": 1532,
        "height": 1027
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-6.png",
        "width": 1536,
        "height": 1024
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-7.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-8.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-9.png",
        "width": 1122,
        "height": 1402
      },
      {
        "src": "/images/gallery/false-ceiling/ceiling-10.png",
        "width": 1086,
        "height": 1449
      }
    ]
  },
  {
    "slug": "hall",
    "images": [
      {
        "src": "/images/gallery/hall/Hall-1.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/hall/Hall-2.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/hall/Hall-3.jpg",
        "width": 2048,
        "height": 1153
      },
      {
        "src": "/images/gallery/hall/HAll-3.png",
        "width": 1342,
        "height": 1172
      },
      {
        "src": "/images/gallery/hall/Hall-4.png",
        "width": 1448,
        "height": 1086
      }
    ]
  },
  {
    "slug": "jhumars",
    "images": [
      {
        "src": "/images/gallery/jhumars/Jhumar-1.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/jhumars/jhumar-2.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/jhumars/Jhumar-3.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/jhumars/Jhumar-4.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/jhumars/jhumar-5.png",
        "width": 1206,
        "height": 1305
      },
      {
        "src": "/images/gallery/jhumars/jhumar-6.png",
        "width": 1086,
        "height": 1448
      }
    ]
  },
  {
    "slug": "kitchen",
    "images": [
      {
        "src": "/images/gallery/kitchen/kitchen%20-2.png",
        "width": 1410,
        "height": 1115
      },
      {
        "src": "/images/gallery/kitchen/kitchen%201.png",
        "width": 1086,
        "height": 1448
      }
    ]
  },
  {
    "slug": "light",
    "images": [
      {
        "src": "/images/gallery/light/Complete%20lighting%20option%20availed.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/light/Light-1.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/light/light-2.png",
        "width": 1023,
        "height": 1537
      },
      {
        "src": "/images/gallery/light/Light-3.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/light/Light-4.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/light/LIght-6.jpeg",
        "width": 722,
        "height": 1600
      }
    ]
  },
  {
    "slug": "office",
    "images": [
      {
        "src": "/images/gallery/office/office%205.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/images/gallery/office/office-1.png",
        "width": 941,
        "height": 1672
      },
      {
        "src": "/images/gallery/office/office-2.png",
        "width": 1000,
        "height": 1573
      },
      {
        "src": "/images/gallery/office/office7.png",
        "width": 1086,
        "height": 1448
      }
    ]
  },
  {
    "slug": "sanitary",
    "images": [
      {
        "src": "/images/gallery/sanitary/cover.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/sanitary/godown.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/sanitary/nerolac%20paint.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/sanitary/pipes.png",
        "width": 1402,
        "height": 1122
      },
      {
        "src": "/images/gallery/sanitary/sanitary%20and%20basins.png",
        "width": 1536,
        "height": 1024
      },
      {
        "src": "/images/gallery/sanitary/toilet.png",
        "width": 1448,
        "height": 1086
      }
    ]
  },
  {
    "slug": "tv-unit-design",
    "images": [
      {
        "src": "/images/gallery/tv-unit-design/tv1.png",
        "width": 1448,
        "height": 1086
      },
      {
        "src": "/images/gallery/tv-unit-design/tv2.png",
        "width": 1086,
        "height": 1448
      },
      {
        "src": "/images/gallery/tv-unit-design/tv3.png",
        "width": 1082,
        "height": 1454
      },
      {
        "src": "/images/gallery/tv-unit-design/tv4.png",
        "width": 1086,
        "height": 1448
      }
    ]
  }
];
