// AUTO-GENERATED by scripts/build-video-manifest.mjs — do not edit by hand.
// Regenerate with `npm run videos:manifest` (runs automatically on build).

import type { VideoManifest } from "@/types/video";

export const videoManifest: VideoManifest = [
  {
    "name": "cover",
    "src": "/videos/cover.mp4"
  },
  {
    "name": "video3",
    "src": "/videos/video3.mp4"
  },
  {
    "name": "video4",
    "src": "/videos/video4.mp4"
  }
];
