import type { Video } from "@/types/video";
import { videoManifest } from "./video-manifest.generated";

/**
 * Walkthrough video reader.
 *
 * Reads the build-time manifest (generated by scripts/build-video-manifest.mjs)
 * so the runtime never touches the filesystem — Cloudflare Workers compatible,
 * same as the gallery. Dropping an mp4 into public/videos adds it on the next
 * build; removing one removes it. The file named cover.* is the featured video.
 */

function titleFromName(name: string): string {
  return name
    .replace(/[-_]+/g, " ")
    // Add a space between letters and digits, e.g. "video3" -> "video 3".
    .replace(/([a-z])(\d)/gi, "$1 $2")
    .trim()
    .split(" ")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** All walkthrough videos, cover (featured) first. */
export function getVideos(): Video[] {
  return videoManifest.map((entry) => ({
    name: entry.name,
    title: titleFromName(entry.name),
    src: entry.src,
    poster: entry.poster,
    featured: entry.name.toLowerCase() === "cover",
  }));
}
